name: Daily Reset

on:
  schedule:
    - cron: "30 14 * * *"   # JST 23:30
  workflow_dispatch:        # 手動実行
  push:                     # ← automation を削除
    branches:
      - main                # main に push したときだけ動く（必要なら）

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: 全リセット
        run: |
          curl -X POST https://number-board.onrender.com/reset

      - name: ステータス変更（お休み入力中）
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"status":"お休み入力中"}' \
            https://number-board.onrender.com/setStatus
